# coding: utf-8

# flake8: noqa

"""
    Музыкальная бибилотека API

    API для управления плейлистами и треками в музыкальной бибилотеке  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import apis into sdk package
from swagger_client.api.playlists_api import PlaylistsApi
# import ApiClient
from swagger_client.api_client import ApiClient
from swagger_client.configuration import Configuration
# import models into sdk package
