# coding: utf-8

"""
    Музыкальная бибилотека API

    API для управления плейлистами и треками в музыкальной бибилотеке  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from swagger_client.api_client import ApiClient


class PlaylistsApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def playlists_get(self, **kwargs):  # noqa: E501
        """Получить все плейлисты  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.playlists_get(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.playlists_get_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.playlists_get_with_http_info(**kwargs)  # noqa: E501
            return data

    def playlists_get_with_http_info(self, **kwargs):  # noqa: E501
        """Получить все плейлисты  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.playlists_get_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = []  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method playlists_get" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/playlists', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def playlists_playlist_id_delete(self, playlist_id, **kwargs):  # noqa: E501
        """Удалить плейлист по ID  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.playlists_playlist_id_delete(playlist_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int playlist_id: ID of the playlist (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.playlists_playlist_id_delete_with_http_info(playlist_id, **kwargs)  # noqa: E501
        else:
            (data) = self.playlists_playlist_id_delete_with_http_info(playlist_id, **kwargs)  # noqa: E501
            return data

    def playlists_playlist_id_delete_with_http_info(self, playlist_id, **kwargs):  # noqa: E501
        """Удалить плейлист по ID  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.playlists_playlist_id_delete_with_http_info(playlist_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int playlist_id: ID of the playlist (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['playlist_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method playlists_playlist_id_delete" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'playlist_id' is set
        if ('playlist_id' not in params or
                params['playlist_id'] is None):
            raise ValueError("Missing the required parameter `playlist_id` when calling `playlists_playlist_id_delete`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'playlist_id' in params:
            path_params['playlistId'] = params['playlist_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/playlists/{playlistId}', 'DELETE',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def playlists_playlist_id_get(self, playlist_id, **kwargs):  # noqa: E501
        """Получить плейлист по ID  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.playlists_playlist_id_get(playlist_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int playlist_id: ID of the playlist (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.playlists_playlist_id_get_with_http_info(playlist_id, **kwargs)  # noqa: E501
        else:
            (data) = self.playlists_playlist_id_get_with_http_info(playlist_id, **kwargs)  # noqa: E501
            return data

    def playlists_playlist_id_get_with_http_info(self, playlist_id, **kwargs):  # noqa: E501
        """Получить плейлист по ID  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.playlists_playlist_id_get_with_http_info(playlist_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int playlist_id: ID of the playlist (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['playlist_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method playlists_playlist_id_get" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'playlist_id' is set
        if ('playlist_id' not in params or
                params['playlist_id'] is None):
            raise ValueError("Missing the required parameter `playlist_id` when calling `playlists_playlist_id_get`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'playlist_id' in params:
            path_params['playlistId'] = params['playlist_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/playlists/{playlistId}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def playlists_playlist_id_put(self, playlist_id, **kwargs):  # noqa: E501
        """Обновить плейлист по ID  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.playlists_playlist_id_put(playlist_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int playlist_id: ID of the playlist (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.playlists_playlist_id_put_with_http_info(playlist_id, **kwargs)  # noqa: E501
        else:
            (data) = self.playlists_playlist_id_put_with_http_info(playlist_id, **kwargs)  # noqa: E501
            return data

    def playlists_playlist_id_put_with_http_info(self, playlist_id, **kwargs):  # noqa: E501
        """Обновить плейлист по ID  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.playlists_playlist_id_put_with_http_info(playlist_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int playlist_id: ID of the playlist (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['playlist_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method playlists_playlist_id_put" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'playlist_id' is set
        if ('playlist_id' not in params or
                params['playlist_id'] is None):
            raise ValueError("Missing the required parameter `playlist_id` when calling `playlists_playlist_id_put`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'playlist_id' in params:
            path_params['playlistId'] = params['playlist_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/playlists/{playlistId}', 'PUT',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def playlists_playlist_id_tracks_get(self, playlist_id, **kwargs):  # noqa: E501
        """Получить все треки в плейлисте  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.playlists_playlist_id_tracks_get(playlist_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int playlist_id: ID of the playlist (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.playlists_playlist_id_tracks_get_with_http_info(playlist_id, **kwargs)  # noqa: E501
        else:
            (data) = self.playlists_playlist_id_tracks_get_with_http_info(playlist_id, **kwargs)  # noqa: E501
            return data

    def playlists_playlist_id_tracks_get_with_http_info(self, playlist_id, **kwargs):  # noqa: E501
        """Получить все треки в плейлисте  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.playlists_playlist_id_tracks_get_with_http_info(playlist_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int playlist_id: ID of the playlist (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['playlist_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method playlists_playlist_id_tracks_get" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'playlist_id' is set
        if ('playlist_id' not in params or
                params['playlist_id'] is None):
            raise ValueError("Missing the required parameter `playlist_id` when calling `playlists_playlist_id_tracks_get`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'playlist_id' in params:
            path_params['playlistId'] = params['playlist_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/playlists/{playlistId}/tracks', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def playlists_playlist_id_tracks_post(self, playlist_id, **kwargs):  # noqa: E501
        """Добавить новый трек в плейлист  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.playlists_playlist_id_tracks_post(playlist_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int playlist_id: ID of the playlist (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.playlists_playlist_id_tracks_post_with_http_info(playlist_id, **kwargs)  # noqa: E501
        else:
            (data) = self.playlists_playlist_id_tracks_post_with_http_info(playlist_id, **kwargs)  # noqa: E501
            return data

    def playlists_playlist_id_tracks_post_with_http_info(self, playlist_id, **kwargs):  # noqa: E501
        """Добавить новый трек в плейлист  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.playlists_playlist_id_tracks_post_with_http_info(playlist_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int playlist_id: ID of the playlist (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['playlist_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method playlists_playlist_id_tracks_post" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'playlist_id' is set
        if ('playlist_id' not in params or
                params['playlist_id'] is None):
            raise ValueError("Missing the required parameter `playlist_id` when calling `playlists_playlist_id_tracks_post`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'playlist_id' in params:
            path_params['playlistId'] = params['playlist_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/playlists/{playlistId}/tracks', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def playlists_playlist_id_tracks_track_id_delete(self, playlist_id, track_id, **kwargs):  # noqa: E501
        """Удалить трек по ID  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.playlists_playlist_id_tracks_track_id_delete(playlist_id, track_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int playlist_id: ID of the playlist (required)
        :param int track_id: ID of the track (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.playlists_playlist_id_tracks_track_id_delete_with_http_info(playlist_id, track_id, **kwargs)  # noqa: E501
        else:
            (data) = self.playlists_playlist_id_tracks_track_id_delete_with_http_info(playlist_id, track_id, **kwargs)  # noqa: E501
            return data

    def playlists_playlist_id_tracks_track_id_delete_with_http_info(self, playlist_id, track_id, **kwargs):  # noqa: E501
        """Удалить трек по ID  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.playlists_playlist_id_tracks_track_id_delete_with_http_info(playlist_id, track_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int playlist_id: ID of the playlist (required)
        :param int track_id: ID of the track (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['playlist_id', 'track_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method playlists_playlist_id_tracks_track_id_delete" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'playlist_id' is set
        if ('playlist_id' not in params or
                params['playlist_id'] is None):
            raise ValueError("Missing the required parameter `playlist_id` when calling `playlists_playlist_id_tracks_track_id_delete`")  # noqa: E501
        # verify the required parameter 'track_id' is set
        if ('track_id' not in params or
                params['track_id'] is None):
            raise ValueError("Missing the required parameter `track_id` when calling `playlists_playlist_id_tracks_track_id_delete`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'playlist_id' in params:
            path_params['playlistId'] = params['playlist_id']  # noqa: E501
        if 'track_id' in params:
            path_params['trackId'] = params['track_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/playlists/{playlistId}/tracks/{trackId}', 'DELETE',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def playlists_playlist_id_tracks_track_id_get(self, playlist_id, track_id, **kwargs):  # noqa: E501
        """Получить трек по ID  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.playlists_playlist_id_tracks_track_id_get(playlist_id, track_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int playlist_id: ID of the playlist (required)
        :param int track_id: ID of the track (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.playlists_playlist_id_tracks_track_id_get_with_http_info(playlist_id, track_id, **kwargs)  # noqa: E501
        else:
            (data) = self.playlists_playlist_id_tracks_track_id_get_with_http_info(playlist_id, track_id, **kwargs)  # noqa: E501
            return data

    def playlists_playlist_id_tracks_track_id_get_with_http_info(self, playlist_id, track_id, **kwargs):  # noqa: E501
        """Получить трек по ID  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.playlists_playlist_id_tracks_track_id_get_with_http_info(playlist_id, track_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int playlist_id: ID of the playlist (required)
        :param int track_id: ID of the track (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['playlist_id', 'track_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method playlists_playlist_id_tracks_track_id_get" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'playlist_id' is set
        if ('playlist_id' not in params or
                params['playlist_id'] is None):
            raise ValueError("Missing the required parameter `playlist_id` when calling `playlists_playlist_id_tracks_track_id_get`")  # noqa: E501
        # verify the required parameter 'track_id' is set
        if ('track_id' not in params or
                params['track_id'] is None):
            raise ValueError("Missing the required parameter `track_id` when calling `playlists_playlist_id_tracks_track_id_get`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'playlist_id' in params:
            path_params['playlistId'] = params['playlist_id']  # noqa: E501
        if 'track_id' in params:
            path_params['trackId'] = params['track_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/playlists/{playlistId}/tracks/{trackId}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def playlists_playlist_id_tracks_track_id_put(self, playlist_id, track_id, **kwargs):  # noqa: E501
        """Обновить трек по ID  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.playlists_playlist_id_tracks_track_id_put(playlist_id, track_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int playlist_id: ID of the playlist (required)
        :param int track_id: ID of the track (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.playlists_playlist_id_tracks_track_id_put_with_http_info(playlist_id, track_id, **kwargs)  # noqa: E501
        else:
            (data) = self.playlists_playlist_id_tracks_track_id_put_with_http_info(playlist_id, track_id, **kwargs)  # noqa: E501
            return data

    def playlists_playlist_id_tracks_track_id_put_with_http_info(self, playlist_id, track_id, **kwargs):  # noqa: E501
        """Обновить трек по ID  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.playlists_playlist_id_tracks_track_id_put_with_http_info(playlist_id, track_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int playlist_id: ID of the playlist (required)
        :param int track_id: ID of the track (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['playlist_id', 'track_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method playlists_playlist_id_tracks_track_id_put" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'playlist_id' is set
        if ('playlist_id' not in params or
                params['playlist_id'] is None):
            raise ValueError("Missing the required parameter `playlist_id` when calling `playlists_playlist_id_tracks_track_id_put`")  # noqa: E501
        # verify the required parameter 'track_id' is set
        if ('track_id' not in params or
                params['track_id'] is None):
            raise ValueError("Missing the required parameter `track_id` when calling `playlists_playlist_id_tracks_track_id_put`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'playlist_id' in params:
            path_params['playlistId'] = params['playlist_id']  # noqa: E501
        if 'track_id' in params:
            path_params['trackId'] = params['track_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/playlists/{playlistId}/tracks/{trackId}', 'PUT',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def playlists_post(self, **kwargs):  # noqa: E501
        """Создать новый плейлист  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.playlists_post(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.playlists_post_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.playlists_post_with_http_info(**kwargs)  # noqa: E501
            return data

    def playlists_post_with_http_info(self, **kwargs):  # noqa: E501
        """Создать новый плейлист  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.playlists_post_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = []  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method playlists_post" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/playlists', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
