# coding: utf-8

# flake8: noqa
"""
    Музыкальная бибилотека API

    API для управления плейлистами и треками в музыкальной бибилотеке  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import models into model package
