# coding: utf-8

"""
    Музыкальная бибилотека API

    API для управления плейлистами и треками в музыкальной бибилотеке  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.playlists_api import PlaylistsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestPlaylistsApi(unittest.TestCase):
    """PlaylistsApi unit test stubs"""

    def setUp(self):
        self.api = PlaylistsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_playlists_get(self):
        """Test case for playlists_get

        Получить все плейлисты  # noqa: E501
        """
        pass

    def test_playlists_playlist_id_delete(self):
        """Test case for playlists_playlist_id_delete

        Удалить плейлист по ID  # noqa: E501
        """
        pass

    def test_playlists_playlist_id_get(self):
        """Test case for playlists_playlist_id_get

        Получить плейлист по ID  # noqa: E501
        """
        pass

    def test_playlists_playlist_id_put(self):
        """Test case for playlists_playlist_id_put

        Обновить плейлист по ID  # noqa: E501
        """
        pass

    def test_playlists_playlist_id_tracks_get(self):
        """Test case for playlists_playlist_id_tracks_get

        Получить все треки в плейлисте  # noqa: E501
        """
        pass

    def test_playlists_playlist_id_tracks_post(self):
        """Test case for playlists_playlist_id_tracks_post

        Добавить новый трек в плейлист  # noqa: E501
        """
        pass

    def test_playlists_playlist_id_tracks_track_id_delete(self):
        """Test case for playlists_playlist_id_tracks_track_id_delete

        Удалить трек по ID  # noqa: E501
        """
        pass

    def test_playlists_playlist_id_tracks_track_id_get(self):
        """Test case for playlists_playlist_id_tracks_track_id_get

        Получить трек по ID  # noqa: E501
        """
        pass

    def test_playlists_playlist_id_tracks_track_id_put(self):
        """Test case for playlists_playlist_id_tracks_track_id_put

        Обновить трек по ID  # noqa: E501
        """
        pass

    def test_playlists_post(self):
        """Test case for playlists_post

        Создать новый плейлист  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
